### ISSUE TITLE
Are there any plans to support Chinese?

### ISSUE THREAD

**Issue by wmailn** [openwisp/openwisp-radius#184]
I am in China and hope to support Chinese language in the future.

**Comment by nemesisdesign** [comment]
There's no plans to translate the UI in this phase because OpenWISP is evolving fast. However that should not be a problem because OpenWISP RADIUS is not meant to be used by end users, end users are meant to use https://github.com/openwisp/openwisp-wifi-login-pages/ which supports multi-language and you can write your own text.
