### ISSUE TITLE
Unable to make changes for custom user in Admin panel

### ISSUE THREAD

**Issue by chanduaki** [openwisp/openwisp-radius#236]
# summary

Created an customer user model

In settings.py replaced
AUTH_USER_MODEL = '<appname>.CustomUser'

In admin.py (app)

class CustomUserAdmin(admin.ModelAdmin):
    Model=CustomUser
    list_display=('phone_number', 'is_approved')

admin.site.registered(CustomUser, CustomUserAdmin)

# What I am seeing?

Same portal no changes are happening

# what I have to see?

Need to apply new changes In the portal

`Note `: (important)
For  other models changes are reflecting, for only custom user I am unable to change

**Comment by pandafy** [comment]
Hey @chanduaki! Your issue is not related to OpenWISP but Django. I will suggest you to read [Substituting a custom User model](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#substituting-a-custom-user-model) or ask for help in [django-users mailing list](https://groups.google.com/group/django-users).

Cheers!

**Comment by nemesisdesign** [comment]
@chanduaki Follow the instructions in https://openwisp-radius.readthedocs.io/en/latest/developer/how_to_extend.html, if you have question use the [OpenWISP Support channels](https://openwisp.org/support.html).
