### ISSUE TITLE
[change] Users signup should respect the stricter verification settings of org

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-radius#304]
After https://github.com/openwisp/openwisp-radius/issues/297

Suppose two organizations (further abbreviated as org.):
1. Org A needs no identity verification for its users.
2. Org B needs identity verification for its users.

If a user registered with org A tries to login into org B then there is no verification happens of that user and the user is authenticated and authorized to use other things.

So, if the org needs verification then the user should be verified before adding that user to the group of that org.

**Comment by nemesisdesign** [comment]
I think that to discern users who are verified and not who we should add a model method which checks whether the registered_user.is_verified is True and registered_user.method is not unspecified or email. Having this as a model method is useful because it will allow the method to be overridden if needed.

**Comment by pandafy** [comment]
I have a little confusion regarding the flow of cross-organization registration. 

**The problem:**

1. User has already registered to organization A. Organization A does not require identity verification, user is unverified. 
2. User tries to register to organization B, where he gets notified that he has already registered to organization A (409 conflict) 
3. User tries to login via URL for organization B (`radius/organization/org-b/account/token/`), but organization B requires identity verification.

**Questions:** 

1. What should we return in response to step 3? Should we return that the user needs to verify identity? 
This information can be used by wifi-login-pages to render the identity verification rule. 

2. How to decide which verification method to use (SMS or other)? 
Ideally, users should have the freedom to choose any verification method. 
I am not sure about this, but we might need to add another view in wifi-login-pages.

**Comment by nemesisdesign** [comment]
> I have a little confusion regarding the flow of cross-organization registration.
> 
> **The problem:**
> 
> 1. User has already registered to organization A. Organization A does not require identity verification, user is unverified.
> 2. User tries to register to organization B, where he gets notified that he has already registered to organization A (409 conflict)
> 3. User tries to login via URL for organization B (`radius/organization/org-b/account/token/`), but organization B requires identity verification.

I think for this release we can simply return 403 if this happens to avoid a security breach.

> **Questions:**
> 
> 1. What should we return in response to step 3? Should we return that the user needs to verify identity?
>    This information can be used by wifi-login-pages to render the identity verification rule.
> 2. How to decide which verification method to use (SMS or other)?
>    Ideally, users should have the freedom to choose any verification method.
>    I am not sure about this, but we might need to add another view in wifi-login-pages.

In the future release we should change it so that when logging in, the user has to choose a verification method, should be flagged as not verified and should initiate the verification process.

We should also ensure that when the user goes back to use the service which does not require identity verification it can still access it and use it fine (we should test this with wifi-login-pages).
