### ISSUE TITLE
[bug] RadiusAccounting: accounting on closed session should re-open it

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#322]
If a session is flagged as closed but interim updates keep coming, it means the session was not really closed (which in itself is another issue which users will have to deal depending on their specific installation), on the openwisp radius side we should ensure the accounting request does not fail.

**Here's how to replicate it:**

- create a radius session with its own unique_id, flag it as terminated
- send an interim update request, eg:

```
curl -X POST "http://localhost:8000/api/v1/freeradius/accounting/" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"status_type\": \"Interim-Update\", \"session_id\": \"405448b5b78861da\", \"unique_id\": \"5b24f4f88545927940cf1f12e9dc70a2\", \"username\": \"username-here\", \"realm\": \"NULL\", \"nas_ip_address\": \"127.0.0.1\", \"nas_port_id\": \"2128\", \"nas_port_type\": \"Ethernet\", \"session_time\": \"3127\", \"authentication\": \"RADIUS\", \"input_octets\": \"2506645\", \"output_octets\": \"33801977\", \"called_station_id\": \"00:00:00:00:00:11:gw\", \"calling_station_id\": \"00:00:00:00:00:22\", \"terminate_cause\": \"\", \"service_type\": \"Login-User\", \"framed_protocol\": \"\", \"framed_ip_address\": \"172.28.121.95\"}"
```

**Expected result:**

200 ok, request input/output packets and time shall be updated, it shall be flagged as still open.

**Current Result:**

```
{"unique_id":["accounting with this accounting unique ID already exists."]}
```

It seems it's trying to create a new radius accounting record instead of updating the existing one.

**Comment by codesankalp** [comment]
When I am trying the above steps it is re-opening it. I did:
1. Terminated the radius session.
2. Make the curl request with the unique_id and session_id of that session. I am not getting any errors and a new radius session is also not created after this (If I change the unique id and retry then it will create a new session but still no errors are shown).
3. Also In the admin dashboard termination cause becomes empty as requested in the request data.

**Comment by nemesisdesign** [comment]
> When I am trying the above steps it is re-opening it. I did:
> 
> 1. Terminated the radius session.
> 2. Make the curl request with the unique_id and session_id of that session. I am not getting any errors and a new radius session is also not created after this (If I change the unique id and retry then it will create a new session but still no errors are shown).
> 3. Also In the admin dashboard termination cause becomes empty as requested in the request data.

I tested this locally and I see there's no error as you say, not sure why in prod I see errors, I will keep testing. Anyway, I see also locally that the session is still flagged as closed even if the interim-update keeps coming, which is not right, because if interim updates keep coming it means the session is still open, can you  least handling this please? If interim updates comes for a session which has a stop time, the stop time should be cleared.

**Comment by nemesisdesign** [comment]
Closing for now because the only issue that I was able to replicate consistently has been fixed. Will reopen if I notice the same problem again.

**Comment by nemesisdesign** [comment]
I have noticed the same problem in production, from the freeradius logs:

```
{"unique_id":["accounting with this accounting unique ID already exists."]}
```

The first step we should do is to log failed requests with warning level, including the details of the accounting requests, so then we can try to replicate it.

**Comment by pandafy** [comment]
The `Interim-Update` request will get rejected if a user has started a session with another organization. Consider the following scenario

There are two organizations **OrgA** and **OrgB**. 

1. The user first logs into the RADIUS service of **OrgA**. 
2. A RadiusAccounting object is created for the user for **OrgA**, let's call it **sessionA**
3. Without logging out from the RADIUS service of **OrgA**, the user logs into the RADIUS service of **OrgB**. 
This updates the organization field of RadiusToken of the user and openwisp-radius closes the previous RadiusAccounting session, **sessionA**. This is the code that is responsible for this operation: 
https://github.com/openwisp/openwisp-radius/blob/4d10438e274768c5971e0fa681dabdf34fbf4f52/openwisp_radius/api/views.py#L210-L230

But the FreeRADIUS (or any other RADIUS server) is not aware of this change. It does not know that the **sessionA** was closed in the openwisp-radius database. Therefore, it keeps sending `Interim-Update` requests. 

The `AccountingView` which handles these requests filters the queryset according to the organization of RadiusToken of the user. 

https://github.com/openwisp/openwisp-radius/blob/4d10438e274768c5971e0fa681dabdf34fbf4f52/openwisp_radius/api/freeradius_views.py#L405-L406

Remember that the user has logged into **OrgB** and its RadiusToken has **OrgB** as its organization. Therefore, the queryset in the code below only contains RadiusAccounting sessions that belong to **OrgB**. 

https://github.com/openwisp/openwisp-radius/blob/4d10438e274768c5971e0fa681dabdf34fbf4f52/openwisp_radius/api/freeradius_views.py#L427-L436

While handling an `Interim-Update` request for **sessionA**, the code looks for **sessionA** in a queryset which only contains RadiusAccounting objects for **OrgB**. Thus, it raises a `DoesNotExist` exception and executes goes to the `except` block. 

The code in the `except` block tries to create a new `RadiusAccounting` object with the data received. But, it fails to do so because **sessionA** already exists and the `unique_id` is set to be unique in the models.

**Comment by nemesisdesign** [comment]
So as a solution, we could do the following:

- check whether the validation error is in the unique_id key
- fetch the radius accounting with the unique_id, then check whether its org is different from the current org and if yes, just skip

**Comment by pandafy** [comment]
@Aryamanz29 are you working on this issue?

**Comment by Aryamanz29** [comment]
> @Aryamanz29 are you working on this issue?

I'm not @pandafy 
I don't know how it get referenced 😅
